In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("final_data.csv")
data.head()

,Unnamed: 0,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,0,29.85,29.85,0,1,0,0,1,1,...,0,0,1,0,1,0,0,0,0,0
1,1,0,56.95,1889.50,0,0,1,1,0,1,...,0,0,0,1,0,0,1,0,0,0
2,2,0,53.85,108.15,1,0,1,1,0,1,...,0,0,0,1,1,0,0,0,0,0
3,3,0,42.30,1840.75,0,0,1,1,0,1,...,1,0,0,0,0,0,0,1,0,0
4,4,0,70.70,151.65,1,1,0,1,0,1,...,0,0,1,0,1,0,0,0,0,0

In [4]:
data.drop(columns=["Unnamed: 0"],inplace=True)

In [5]:
data.head()

,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29.85,29.85,0,1,0,0,1,1,0,...,0,0,1,0,1,0,0,0,0,0
1,0,56.95,1889.50,0,0,1,1,0,1,0,...,0,0,0,1,0,0,1,0,0,0
2,0,53.85,108.15,1,0,1,1,0,1,0,...,0,0,0,1,1,0,0,0,0,0
3,0,42.30,1840.75,0,0,1,1,0,1,0,...,1,0,0,0,0,0,0,1,0,0
4,0,70.70,151.65,1,1,0,1,0,1,0,...,0,0,1,0,1,0,0,0,0,0

In [60]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 51 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   SeniorCitizen                            7032 non-null   int64
 1   MonthlyCharges                           7032 non-null   float64
 2   TotalCharges                             7032 non-null   float64
 3   Churn                                    7032 non-null   int64
 4   gender_Female                            7032 non-null   int64
 5   gender_Male                              7032 non-null   int64
 6   Partner_No                               7032 non-null   int64
 7   Partner_Yes                              7032 non-null   int64
 8   Dependents_No                            7032 non-null   int64
 9   Dependents_Yes                           7032 non-null   int64
 10  PhoneService_No                          7032 non-null   int64
 11  PhoneService_Yes                         7032 non-null   int64
 12  MultipleLines_No                         7032 non-null   int64
 13  MultipleLines_No phone service           7032 non-null   int64
 14  MultipleLines_Yes                        7032 non-null   int64
 15  InternetService_DSL                      7032 non-null   int64
 16  InternetService_Fiber optic              7032 non-null   int64
 17  InternetService_No                       7032 non-null   int64
 18  OnlineSecurity_No                        7032 non-null   int64
 19  OnlineSecurity_No internet service       7032 non-null   int64
 20  OnlineSecurity_Yes                       7032 non-null   int64
 21  OnlineBackup_No                          7032 non-null   int64
 22  OnlineBackup_No internet service         7032 non-null   int64
 23  OnlineBackup_Yes                         7032 non-null   int64
 24  DeviceProtection_No                      7032 non-null   int64
 25  DeviceProtection_No internet service     7032 non-null   int64
 26  DeviceProtection_Yes                     7032 non-null   int64
 27  TechSupport_No                           7032 non-null   int64
 28  TechSupport_No internet service          7032 non-null   int64
 29  TechSupport_Yes                          7032 non-null   int64
 30  StreamingTV_No                           7032 non-null   int64
 31  StreamingTV_No internet service          7032 non-null   int64
 32  StreamingTV_Yes                          7032 non-null   int64
 33  StreamingMovies_No                       7032 non-null   int64
 34  StreamingMovies_No internet service      7032 non-null   int64
 35  StreamingMovies_Yes                      7032 non-null   int64
 36  Contract_Month-to-month                  7032 non-null   int64
 37  Contract_One year                        7032 non-null   int64
 38  Contract_Two year                        7032 non-null   int64
 39  PaperlessBilling_No                      7032 non-null   int64
 40  PaperlessBilling_Yes                     7032 non-null   int64
 41  PaymentMethod_Bank transfer (automatic)  7032 non-null   int64
 42  PaymentMethod_Credit card (automatic)    7032 non-null   int64
 43  PaymentMethod_Electronic check           7032 non-null   int64
 44  PaymentMethod_Mailed check               7032 non-null   int64
 45  tenure_group_1 - 12                      7032 non-null   int64
 46  tenure_group_13 - 24                     7032 non-null   int64
 47  tenure_group_25 - 36                     7032 non-null   int64
 48  tenure_group_37 - 48                     7032 non-null   int64
 49  tenure_group_49 - 60                     7032 non-null   int64
 50  tenure_group_61 - 72                     7032 non-null   int64
dtypes: float64(2), int64(49)
memory usage: 2.7 MB

In [8]:
X=data.drop(columns=['Churn'])
y=data['Churn']

In [11]:
X.shape

(7032, 50)

In [ ]:
y.shape

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=77)

In [24]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((4922, 50), (2110, 50), (4922,), (2110,))

In [26]:
from sklearn.tree import DecisionTreeClassifier

In [35]:
model1=DecisionTreeClassifier(criterion="entropy",splitter="random",max_depth=5,min_samples_split=7,random_state=30)

model1.fit(X_train,y_train)
model1.score(X_test,y_test)

0.7933649289099526

In [38]:
from sklearn.metrics import classification_report
y_pred=model1.predict(X_test)
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.82      0.92      0.87      1539
           1       0.67      0.46      0.55       571

    accuracy                           0.79      2110
   macro avg       0.75      0.69      0.71      2110
weighted avg       0.78      0.79      0.78      2110

In [41]:
from imblearn.combine import SMOTEENN

sm = SMOTEENN(random_state=42)

X_resampled1, y_resampled1 = sm.fit_resample(X, y)

In [42]:
xr_train1,xr_test1,yr_train1,yr_test1=train_test_split(X_resampled1, y_resampled1,test_size=0.2)

In [46]:
from sklearn.ensemble import RandomForestClassifier
model_rf=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [49]:
model_rf.fit(xr_train1,yr_train1)
yr_predict1 = model_rf.predict(xr_test1)
model_score_r1 = model_rf.score(xr_test1, yr_test1)

In [51]:
print(model_score_r1)
print(classification_report(yr_test1, yr_predict1))

0.940677966101695
              precision    recall  f1-score   support

           0       0.96      0.90      0.93       525
           1       0.93      0.97      0.95       655

    accuracy                           0.94      1180
   macro avg       0.94      0.94      0.94      1180
weighted avg       0.94      0.94      0.94      1180

In [53]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(yr_test1, yr_predict1))

[[474  51]
 [ 19 636]]

In [54]:
# Applying PCA
from sklearn.decomposition import PCA
pca = PCA(0.9)
xr_train_pca = pca.fit_transform(xr_train1)
xr_test_pca = pca.transform(xr_test1)
explained_variance = pca.explained_variance_ratio_

In [55]:
model=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)
model.fit(xr_train_pca,yr_train1)
yr_predict_pca = model.predict(xr_test_pca)
model_score_r_pca = model.score(xr_test_pca, yr_test1)

In [57]:
print(model_score_r_pca)
print(classification_report(yr_test1, yr_predict_pca))

0.7288135593220338
              precision    recall  f1-score   support

           0       0.72      0.65      0.68       525
           1       0.74      0.79      0.76       655

    accuracy                           0.73      1180
   macro avg       0.73      0.72      0.72      1180
weighted avg       0.73      0.73      0.73      1180

In [ ]:
# With PCA, we couldn't see any better results, hence let's finalise the model which was created by RF Classifier, and save the model so that we can use it in a later stage :)

In [58]:
import pickle

In [59]:
pickle.dump(model_rf, open("model.pkl", 'wb'))